name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Compilar EXE com PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=luma.ico --version-file=version.txt luma.py

    - name: Fazer upload do .exe como artefato
      uses: actions/upload-artifact@v3
      with:
        name: luma-exe
        path: dist/luma.exe
