name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install pyinstaller
        pip install -r requirements.txt || echo "Sem requirements.txt"

    - name: Compilar EXE com PyInstaller
      run: |
        pyinstaller --onefile --noconsole --icon=luma.ico new.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: luma-exe
        path: dist/new.exe
